/* eslint-disable react/no-unescaped-entities */
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/21UGHU1bB4d
 */
import Link from "next/link"
import Header from "@/components/ui/header"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export default function Home() {
  return (
    <div className="flex flex-col min-h-[100vh] lowercase">
<Header/>
      <main className="flex-1">
        <section className="w-full flex h-96 md:h-auto justify-center items-center bg-baby dark:bg-black py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold text-cream tracking-tighter text-pretty sm:text-5xl lg:text-6xl">
                   Work w/ Pulse
                </h1>
                <p className="mx-auto text-lightrose text-pretty text-lg/snug md:text-xl lg:text-2xl xl:text-3xl">
                  Are you a builder? <br className="sm:hidden"/>
                  <span>Join our contract team today.</span>
                </p>
              </div>
              <div className="w-full max-w-sm space-y-2">
                <form className="flex space-x-2">
                  <Input className="max-w-lg flex-1" placeholder="enter your email" type="email" />
                  <Button type="submit">blast off 🚀</Button>
                </form>
                <p className="text-xs text-lightrose">
                  Join our email list to get updates.
                  <Link className="pl-2 underline underline-offset-2" href="#">
                    Terms & Conditions
                  </Link>
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full flex justify-center items-center py-12 md:py-24 lg:py-32 bg-amethyst dark:bg-black">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl text-cream font-bold tracking-tighter sm:text-5xl">job opportunities</h2>
                <p className="max-w-[900px] text-lightrose text-base/relaxed md:text-lg/relaxed lg:text-xl/relaxed">
                Become part of our team of experts dedicated to building, managing, and growing communities. we are always hiring engineers, designers, and other freelance contractors on a per-project.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full h-96 flex justify-center items-center py-12 dark:bg-black bg-oyster md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl text-cream font-bold tracking-tighter sm:text-5xl">current offerings</h2>
                <p className="max-w-[900px] text-lightrose text-base/relaxed md:text-lg/relaxed lg:text-xl/relaxed">
                    Please check back later.
                </p>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 bg-rose dark:bg-black sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6">
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <TwitterIcon className="h-4 w-4" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <FacebookIcon className="h-4 w-4" />
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            <InstagramIcon className="h-4 w-4" />
          </Link>
        </nav>
        <p className="text-xs text-cream">
          © 2024 Community Management Agency. All rights reserved.
        </p>
      </footer>
    </div>
  )
}

function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0-4-4H9a4 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function TwitterIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function FacebookIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 12.63 8 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}